# CSS 147 个颜色单词
# https://www.runoob.com/cssref/css-colornames.html

COLORS = {
    "aliceblue": "#F0F8FF",            # 1. AliceBlue
    "antiquewhite": "#FAEBD7",         # 2. AntiqueWhite
    "aqua": "#00FFFF",                 # 3. Aqua
    "aquamarine": "#7FFFD4",           # 4. Aquamarine
    "azure": "#F0FFFF",                # 5. Azure
    "beige": "#F5F5DC",                # 6. Beige
    "bisque": "#FFE4C4",               # 7. Bisque
    "black": "#000000",                # 8. Black
    "blanchedalmond": "#FFEBCD",       # 9. BlanchedAlmond
    "blue": "#0000FF",                 # 10. Blue
    "blueviolet": "#8A2BE2",           # 11. BlueViolet
    "brown": "#A52A2A",                # 12. Brown
    "burlywood": "#DEB887",            # 13. BurlyWood
    "cadetblue": "#5F9EA0",            # 14. CadetBlue
    "chartreuse": "#7FFF00",           # 15. Chartreuse
    "chocolate": "#D2691E",            # 16. Chocolate
    "coral": "#FF7F50",                # 17. Coral
    "cornflowerblue": "#6495ED",       # 18. CornflowerBlue
    "cornsilk": "#FFF8DC",             # 19. Cornsilk
    "crimson": "#DC143C",              # 20. Crimson
    "cyan": "#00FFFF",                 # 21. Cyan
    "darkblue": "#00008B",             # 22. DarkBlue
    "darkcyan": "#008B8B",             # 23. DarkCyan
    "darkgoldenrod": "#B8860B",        # 24. DarkGoldenRod
    "darkgray": "#A9A9A9",             # 25. DarkGray
    "darkgreen": "#006400",            # 26. DarkGreen
    "darkkhaki": "#BDB76B",            # 27. DarkKhaki
    "darkmagenta": "#8B008B",          # 28. DarkMagenta
    "darkolivegreen": "#556B2F",       # 29. DarkOliveGreen
    "darkorange": "#FF8C00",           # 30. DarkOrange
    "darkorchid": "#9932CC",           # 31. DarkOrchid
    "darkred": "#8B0000",              # 32. DarkRed
    "darksalmon": "#E9967A",           # 33. DarkSalmon
    "darkseagreen": "#8FBC8F",         # 34. DarkSeaGreen
    "darkslateblue": "#483D8B",        # 35. DarkSlateBlue
    "darkslategray": "#2F4F4F",        # 36. DarkSlateGray
    "darkturquoise": "#00CED1",        # 37. DarkTurquoise
    "darkviolet": "#9400D3",           # 38. DarkViolet
    "deeppink": "#FF1493",             # 39. DeepPink
    "deepskyblue": "#00BFFF",          # 40. DeepSkyBlue
    "dimgray": "#696969",              # 41. DimGray
    "dodgerblue": "#1E90FF",           # 42. DodgerBlue
    "firebrick": "#B22222",            # 43. FireBrick
    "floralwhite": "#FFFAF0",          # 44. FloralWhite
    "forestgreen": "#228B22",          # 45. ForestGreen
    "fuchsia": "#FF00FF",              # 46. Fuchsia
    "gainsboro": "#DCDCDC",            # 47. Gainsboro
    "ghostwhite": "#F8F8FF",           # 48. GhostWhite
    "gold": "#FFD700",                 # 49. Gold
    "goldenrod": "#DAA520",            # 50. GoldenRod
    "gray": "#808080",                 # 51. Gray
    "green": "#008000",                # 52. Green
    "greenyellow": "#ADFF2F",          # 53. GreenYellow
    "honeydew": "#F0FFF0",             # 54. HoneyDew
    "hotpink": "#FF69B4",              # 55. HotPink
    "indianred": "#CD5C5C",            # 56. IndianRed
    "indigo": "#4B0082",               # 57. Indigo
    "ivory": "#FFFFF0",                # 58. Ivory
    "khaki": "#F0E68C",                # 59. Khaki
    "lavender": "#E6E6FA",             # 60. Lavender
    "lavenderblush": "#FFF0F5",        # 61. LavenderBlush
    "lawngreen": "#7CFC00",            # 62. LawnGreen
    "lemonchiffon": "#FFFACD",         # 63. LemonChiffon
    "lightblue": "#ADD8E6",            # 64. LightBlue
    "lightcoral": "#F08080",           # 65. LightCoral
    "lightcyan": "#E0FFFF",            # 66. LightCyan
    "lightgoldenrodyellow": "#FAFAD2", # 67. LightGoldenRodYellow
    "lightgray": "#D3D3D3",            # 68. LightGray
    "lightgreen": "#90EE90",           # 69. LightGreen
    "lightpink": "#FFB6C1",            # 70. LightPink
    "lightsalmon": "#FFA07A",          # 71. LightSalmon
    "lightseagreen": "#20B2AA",        # 72. LightSeaGreen
    "lightskyblue": "#87CEFA",         # 73. LightSkyBlue
    "lightslategray": "#778899",       # 74. LightSlateGray
    "lightsteelblue": "#B0C4DE",       # 75. LightSteelBlue
    "lightyellow": "#FFFFE0",          # 76. LightYellow
    "lime": "#00FF00",                 # 77. Lime
    "limegreen": "#32CD32",            # 78. LimeGreen
    "linen": "#FAF0E6",                # 79. Linen
    "magenta": "#FF00FF",              # 80. Magenta
    "maroon": "#800000",               # 81. Maroon
    "mediumaquamarine": "#66CDAA",     # 82. MediumAquaMarine
    "mediumblue": "#0000CD",           # 83. MediumBlue
    "mediumorchid": "#BA55D3",         # 84. MediumOrchid
    "mediumpurple": "#9370DB",         # 85. MediumPurple
    "mediumseagreen": "#3CB371",       # 86. MediumSeaGreen
    "mediumslateblue": "#7B68EE",      # 87. MediumSlateBlue
    "mediumspringgreen": "#00FA9A",    # 88. MediumSpringGreen
    "mediumturquoise": "#48D1CC",      # 89. MediumTurquoise
    "mediumvioletred": "#C71585",      # 90. MediumVioletRed
    "midnightblue": "#191970",         # 91. MidnightBlue
    "mintcream": "#F5FFFA",            # 92. MintCream
    "mistyrose": "#FFE4E1",            # 93. MistyRose
    "moccasin": "#FFE4B5",             # 94. Moccasin
    "navajowhite": "#FFDEAD",          # 95. NavajoWhite
    "navy": "#000080",                 # 96. Navy
    "oldlace": "#FDF5E6",              # 97. OldLace
    "olive": "#808000",                # 98. Olive
    "olivedrab": "#6B8E23",            # 99. OliveDrab
    "orange": "#FFA500",               # 100. Orange
    "orangered": "#FF4500",            # 101. OrangeRed
    "orchid": "#DA70D6",               # 102. Orchid
    "palegoldenrod": "#EEE8AA",        # 103. PaleGoldenRod
    "palegreen": "#98FB98",            # 104. PaleGreen
    "paleturquoise": "#AFEEEE",        # 105. PaleTurquoise
    "palevioletred": "#DB7093",        # 106. PaleVioletRed
    "papayawhip": "#FFEFD5",           # 107. PapayaWhip
    "peachpuff": "#FFDAB9",            # 108. PeachPuff
    "peru": "#CD853F",                 # 109. Peru
    "pink": "#FFC0CB",                 # 110. Pink
    "plum": "#DDA0DD",                 # 111. Plum
    "powderblue": "#B0E0E6",           # 112. PowderBlue
    "purple": "#800080",               # 113. Purple
    "red": "#FF0000",                  # 114. Red
    "rosybrown": "#BC8F8F",            # 115. RosyBrown
    "royalblue": "#4169E1",            # 116. RoyalBlue
    "saddlebrown": "#8B4513",          # 117. SaddleBrown
    "salmon": "#FA8072",               # 118. Salmon
    "sandybrown": "#F4A460",           # 119. SandyBrown
    "seagreen": "#2E8B57",             # 120. SeaGreen
    "seashell": "#FFF5EE",             # 121. SeaShell
    "sienna": "#A0522D",               # 122. Sienna
    "silver": "#C0C0C0",               # 123. Silver
    "skyblue": "#87CEEB",              # 124. SkyBlue
    "slateblue": "#6A5ACD",            # 125. SlateBlue
    "slategray": "#708090",            # 126. SlateGray
    "snow": "#FFFAFA",                 # 127. Snow
    "springgreen": "#00FF7F",          # 128. SpringGreen
    "steelblue": "#4682B4",            # 129. SteelBlue
    "tan": "#D2B48C",                  # 130. Tan
    "teal": "#008080",                 # 131. Teal
    "thistle": "#D8BFD8",              # 132. Thistle
    "tomato": "#FF6347",               # 133. Tomato
    "turquoise": "#40E0D0",            # 134. Turquoise
    "violet": "#EE82EE",               # 135. Violet
    "wheat": "#F5DEB3",                # 136. Wheat
    "white": "#FFFFFF",                # 137. White
    "whitesmoke": "#F5F5F5",           # 138. WhiteSmoke
    "yellow": "#FFFF00",               # 139. Yellow
    "yellowgreen": "#9ACD32",          # 140. YellowGreen
    
    "darkgrey": "#A9A9A9",             # 141. DarkGrey (与 darkgray 相同)
    "darkslategrey": "#2F4F4F",        # 142. DarkSlateGrey (与 darkslategray 相同)
    "dimgrey": "#696969",              # 143. DimGrey (与 dimgray 相同)
    "grey": "#808080",                 # 144. Grey（与 gray 相同）
    "lightgrey": "#D3D3D3",            # 145. LightGrey (与 lightgray 相同)
    "lightslategrey": "#778899",       # 146. LightSlateGrey (与 lightslategray 相同)
    "slategrey": "#708090"             # 147. SlateGrey (与 slategray 相同)
}